apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-manager-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-manager-check
  template:
    metadata:
      labels:
        app: my-manager-check
    spec:
      containers:
      - name: my-nodejs-mainapp
        image: hadar7/manager:mainManager
        ports:
        - containerPort: 3000
      - name: my-nodejs-service-reverse
        image: hadar7/manager:svc1
        ports:
        - containerPort: 3005
      - name: my-nodejs-service-charactercount
        image: hadar7/manager:svc2
        ports:
        - containerPort: 3004
      - name: my-nodejs-service-detectlanguage
        image: hadar7/manager:svc7
        ports:
        - containerPort: 3030
      - name: my-nodejs-service-summarize
        image: hadar7/manager:svc8
        ports:
        - containerPort: 3008
      - name: my-python-service-textconversion
        image: hadar7/manager:alternativeSvc1
        ports:
        - containerPort: 5000
      - name: my-python-service-textchain
        image: hadar7/manager:alternativeSvc2
        ports:
        - containerPort: 5001
     

---
apiVersion: v1
kind: Service
metadata:
  name: my-manager-check
spec:
  type: LoadBalancer
  selector:
    app: my-manager-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
